CREATE DATABASE calculatoare1;

CREATE TABLE produse(
Producator CHAR(1) NOT NULL,
Model VARCHAR(4) NOT NULL,
Tip VARCHAR(10) NOT NULL
);

CREATE TABLE pc_uri(
Cod INT NOT NULL,
Model VARCHAR(4) NOT NULL,
Viteza DECIMAL(3,0) NOT NULL,
Ram DECIMAL(3,0) NOT NULL,
Hd DECIMAL(2,0) NOT NULL,
Cd VARCHAR(3) NOT NULL,
Pret FLOAT NOT NULL
);

CREATE TABLE laptop_uri(
Cod INT NOT NULL,
Model VARCHAR(4) NOT NULL,
Viteza DECIMAL(3,0) NOT NULL,
Ram DECIMAL(3,0) NOT NULL,
Hd DECIMAL(2,0) NOT NULL,
Pret FLOAT NOT NULL,
Ecran INT NOT NULL
);

CREATE TABLE imprimante(
Cod INT NOT NULL,
Model VARCHAR(4) NOT NULL,
Color VARCHAR(2) NOT NULL,
Tip VARCHAR(6) NOT NULL,
Pret FLOAT NOT NULL
);